SELECT 'UPDATE TABLE SET COLUMN = ', 'PUT_HERE_YOUR_VALUE' ,  'WHERE UNIQUE_COLUMN = ', 'SELECT_HERE_UNIQUE_COLUMN_KEY_VALUE' FROM TABLE WHERE ID = 

Example :

SELECT 'UPDATE CREDENTIAL SET LOGIN = ', 'USER_001' ,  'WHERE ID = ', ID FROM LOGIN WHERE ID = 1

